run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  govet:
    check-shadowing: true
  revive:
    severity: warning
    confidence: 0.8
  dupl:
    threshold: 100
  goconst:
    min-len:         2
    min-occurrences: 2

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec
  exclude-use-default: false
  exclude:
    - G104
    - G102
    - G304
    - don't use an underscore in package name

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace
