version: '3.8'

volumes:
  postgres_volume:

services:
  calendar:
    container_name: calendar
    build:
      context: .
      dockerfile: ./deploy/calendar/Dockerfile
    environment:
      - "DB_NAME=${DB_NAME}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DB_HOST=${DB_HOST}"
    ports:
      - "7000:7000"
    depends_on:
      - db

  db:
    image: postgres:14-alpine3.15
    environment:
      - "POSTGRES_DB=event-service"
      - "POSTGRES_USER=event-service-user"
      - "POSTGRES_PASSWORD=event-service-password"
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  goose:
    build:
      context: .
      dockerfile: ./deploy/migrations/Dockerfile
    restart: on-failure
    environment:
      - "DB_HOST=${DB_HOST}"
    depends_on:
      - db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

#networks:
#  calendar_net:
#    driver: bridge